version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:3000
    links:
      - mongo:mongo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    environment:
      - VIRTUAL_HOST=${CROWI_SERVER_HOST}
      - MONGO_URI=mongodb://mongo:27017/crowi
      - REDIS_URL=redis://redis:6379/crowi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/crowi
      - PASSWORD_SEED=${CROWI_PASSWORD_SEED}
      - FILE_UPLOAD=local    # activate this line if you do not want to use AWS for file upload
    command: "dockerize
              -wait tcp://mongo:27017
              -wait tcp://redis:6379
              -wait tcp://elasticsearch:9200
              -timeout 60s
              npm run server:prod"
    volumes:
      - crowi_data:/data
    restart: always

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    restart: always

  redis:
    image: redis:3-alpine
    volumes:
      - redis_data:/data
    restart: always

  elasticsearch:
    image: elasticsearch:5.3-alpine
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
    command:
      - sh
      - -c
      - "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji;
        ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu;
        /docker-entrypoint.sh elasticsearch"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins
      - ./esconfig:/usr/share/elasticsearch/config
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    privileged: true
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=${CROWI_SERVER_HOST}
    restart: always

volumes:
  crowi_data:
  mongo_configdb:
  mongo_db:
  redis_data:
  es_data:
  es_plugins:
